import { Router, Response } from 'express';
import { authenticate, AuthRequest } from '../middleware/auth';
import { supabase } from '../lib/supabase';
import { loadUserMemories } from '../services/memory';

const router = Router();

/**
 * GET /profile/export
 * Exports the user's AI personality profile as a downloadable JSON.
 * This includes: user display name, memory summaries, top topics, and
 * vault metadata (root hashes). Actual message content is excluded for privacy.
 */
router.get('/export', authenticate, async (req: AuthRequest, res: Response) => {
  const userId = req.user!.userId;
  const encryptionKey = req.headers['x-encryption-key'] as string | undefined;

  try {
    // Fetch memory index from DB
    const { data: memoryIndex, error } = await supabase
      .from('mv_memories')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })
      .limit(20);

    if (error) throw error;

    // Load readable memories
    const memories = await loadUserMemories(userId, encryptionKey);

    // Build personality profile
    const profile = {
      version: '1.0',
      exportedAt: new Date().toISOString(),
      vaultId: userId,
      meta: {
        totalSessions: memoryIndex?.length ?? 0,
        decryptedSessions: memories.length,
        oldestMemory: memoryIndex?.[memoryIndex.length - 1]?.created_at ?? null,
        newestMemory: memoryIndex?.[0]?.created_at ?? null,
      },
      // Summaries only — not full message content
      memorySummaries: memories.map((m) => ({
        date: new Date(m.timestamp).toISOString(),
        summary: m.summary,
        messageCount: m.messages?.length ?? 0,
      })),
      // Verifiable proof anchors
      proofAnchors: (memoryIndex ?? []).map((idx: any) => ({
        date: idx.created_at,
        rootHash: idx.root_hash,
        txHash: idx.tx_hash,
        storageUrl: `https://storagescan-galileo.0g.ai/file/${idx.root_hash}`,
        chainUrl: idx.tx_hash ? `https://chainscan-newton.0g.ai/tx/${idx.tx_hash}` : null,
      })),
      // Personality derived from summaries
      personality: {
        description:
          'This is an agent personality snapshot generated by MindVault. ' +
          'It captures the context and topics this AI companion has built up over time.',
        topicsDiscussed: extractTopics(memories.map((m) => m.summary).join(' ')),
        conversationStyle: 'warm, personal, context-aware',
        poweredBy: '0G Compute + 0G Storage',
        network: 'Galileo Testnet',
      },
    };

    res.setHeader('Content-Type', 'application/json');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="mindvault-personality-${Date.now()}.json"`
    );
    res.json(profile);
  } catch (err) {
    console.error('Profile export error:', err);
    res.status(500).json({ error: 'Failed to export personality profile' });
  }
});

/**
 * POST /profile/import
 * Imports a personality profile exported from MindVault (or a compatible format).
 * Only metadata is imported — actual memories stay on 0G Storage.
 */
router.post('/import', authenticate, async (req: AuthRequest, res: Response) => {
  const userId = req.user!.userId;
  const { profile } = req.body;

  if (!profile || !profile.version) {
    return res.status(400).json({ error: 'Invalid personality profile format' });
  }

  try {
    // Validate basic structure
    if (profile.version !== '1.0') {
      return res.status(400).json({ error: 'Unsupported profile version' });
    }

    // Check how many existing memories user has
    const { count } = await supabase
      .from('mv_memories')
      .select('*', { count: 'exact', head: true })
      .eq('user_id', userId);

    res.json({
      imported: true,
      message: `Personality context imported successfully.`,
      existingMemories: count ?? 0,
      importedSummaries: profile.memorySummaries?.length ?? 0,
      note:
        'Your vault memories remain on 0G Storage. This import adds context about your personality for your AI companion.',
    });
  } catch (err) {
    console.error('Profile import error:', err);
    res.status(500).json({ error: 'Failed to import personality profile' });
  }
});

function extractTopics(text: string): string[] {
  // Simple keyword extraction — returns top unique meaningful words
  const stopwords = new Set([
    'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
    'of', 'with', 'by', 'from', 'is', 'was', 'are', 'were', 'be', 'been',
    'have', 'has', 'had', 'do', 'did', 'will', 'would', 'could', 'should',
    'this', 'that', 'these', 'those', 'my', 'your', 'our', 'their', 'its',
    'i', 'you', 'we', 'they', 'he', 'she', 'it', 'me', 'him', 'her', 'us',
    'about', 'how', 'what', 'when', 'where', 'why', 'who', 'which', 'user',
    'discussed', 'talked', 'conversation', 'session', 'ai',
  ]);

  const words = text.toLowerCase().match(/\b[a-z]{4,}\b/g) ?? [];
  const freq: Record<string, number> = {};
  for (const word of words) {
    if (!stopwords.has(word)) freq[word] = (freq[word] ?? 0) + 1;
  }

  return Object.entries(freq)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([word]) => word);
}

export default router;
